// <auto-generated />
using System;
using KoiOrderingSystem_BusinessObject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KoiOrderingSystem_BusinessObject.Migrations
{
    [DbContext(typeof(KoiOrderingSystemContext))]
    partial class KoiOrderingSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("ExchangeRate")
                        .HasColumnType("float");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.Farm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstablishedYear")
                        .HasColumnType("int");

                    b.Property<string>("FarmName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Farms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9442),
                            Description = "A tranquil farm specializing in high-quality koi fish.",
                            EstablishedYear = 2005,
                            FarmName = "Serenity Koi Farm",
                            IsDeleted = false,
                            Location = "Kyoto",
                            ManagerId = 2,
                            UpdatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9442)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9445),
                            Description = "Known for its vibrant and colorful koi varieties.",
                            EstablishedYear = 2010,
                            FarmName = "Golden Pond Koi Farm",
                            IsDeleted = false,
                            Location = "Osaka",
                            ManagerId = 2,
                            UpdatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9445)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9447),
                            Description = "A family-owned farm with a rich history in koi breeding.",
                            EstablishedYear = 2000,
                            FarmName = "Harmony Koi Farm",
                            IsDeleted = false,
                            Location = "Tokyo",
                            ManagerId = 2,
                            UpdatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9447)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9449),
                            Description = "Specializes in rare koi breeds and sustainable farming practices.",
                            EstablishedYear = 2015,
                            FarmName = "Lotus Koi Farm",
                            IsDeleted = false,
                            Location = "Hiroshima",
                            ManagerId = 2,
                            UpdatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9449)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9450),
                            Description = "Offers a serene environment and expert koi care.",
                            EstablishedYear = 2018,
                            FarmName = "Peaceful Waters Koi Farm",
                            IsDeleted = false,
                            Location = "Nara",
                            ManagerId = 2,
                            UpdatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9451)
                        });
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.FarmKoiType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KoiTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("KoiTypeId");

                    b.ToTable("FarmKoiTypes");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.Insurance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Insurances");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.Koi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KoiTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("KoiTypeId");

                    b.ToTable("Kois");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9379),
                            DateAdded = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9376),
                            Description = "Bright orange koi with white spots.",
                            FarmId = 1,
                            HealthStatus = "Healthy",
                            IsDeleted = false,
                            KoiTypeId = 1,
                            Picture = "https://hanoverkoifarms.com/wp-content/uploads/2017/01/great-kohaku-739x1024.jpg",
                            Status = true,
                            UpdatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9379),
                            Weight = 2.3f
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2020, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9384),
                            DateAdded = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9384),
                            Description = "Black and white koi with a smooth pattern.",
                            FarmId = 1,
                            HealthStatus = "Healthy",
                            IsDeleted = false,
                            KoiTypeId = 2,
                            Picture = "https://hanoverkoifarms.com/wp-content/uploads/2017/01/great-kohaku-739x1024.jpg",
                            Status = true,
                            UpdatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9385),
                            Weight = 3.1f
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2021, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9387),
                            DateAdded = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9387),
                            Description = "Golden koi with a shiny coat.",
                            FarmId = 1,
                            HealthStatus = "Under observation",
                            IsDeleted = false,
                            KoiTypeId = 3,
                            Picture = "https://hanoverkoifarms.com/wp-content/uploads/2017/01/great-kohaku-739x1024.jpg",
                            Status = true,
                            UpdatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9388),
                            Weight = 2.8f
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2022, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9389),
                            DateAdded = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9389),
                            Description = "Small blue and orange koi.",
                            FarmId = 1,
                            HealthStatus = "Healthy",
                            IsDeleted = false,
                            KoiTypeId = 4,
                            Picture = "https://hanoverkoifarms.com/wp-content/uploads/2017/01/great-kohaku-739x1024.jpg",
                            Status = true,
                            UpdatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9390),
                            Weight = 1.9f
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(2019, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9392),
                            DateAdded = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9391),
                            Description = "Large white koi with orange spots.",
                            FarmId = 1,
                            HealthStatus = "Healthy",
                            IsDeleted = false,
                            KoiTypeId = 5,
                            Picture = "https://hanoverkoifarms.com/wp-content/uploads/2017/01/great-kohaku-739x1024.jpg",
                            Status = false,
                            UpdatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9392),
                            Weight = 4.2f
                        });
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.KoiByBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KoiTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KoiTypeId");

                    b.ToTable("KoiByBatches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9423),
                            IsDeleted = false,
                            KoiTypeId = 1,
                            Price = 100.00m,
                            Quantity = 10,
                            Size = 5,
                            UpdatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9425)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9429),
                            IsDeleted = false,
                            KoiTypeId = 2,
                            Price = 150.00m,
                            Quantity = 15,
                            Size = 6,
                            UpdatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9430)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9431),
                            IsDeleted = false,
                            KoiTypeId = 3,
                            Price = 80.00m,
                            Quantity = 8,
                            Size = 4,
                            UpdatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9431)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9432),
                            IsDeleted = false,
                            KoiTypeId = 4,
                            Price = 120.00m,
                            Quantity = 12,
                            Size = 7,
                            UpdatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9433)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9433),
                            IsDeleted = false,
                            KoiTypeId = 5,
                            Price = 200.00m,
                            Quantity = 20,
                            Size = 10,
                            UpdatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9434)
                        });
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.KoiOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShippingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("KoiOrders");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.KoiOrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("KoiByBatchId")
                        .HasColumnType("int");

                    b.Property<int?>("KoiId")
                        .HasColumnType("int");

                    b.Property<int>("KoiOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KoiByBatchId")
                        .IsUnique()
                        .HasFilter("[KoiByBatchId] IS NOT NULL");

                    b.HasIndex("KoiId");

                    b.HasIndex("KoiOrderId");

                    b.ToTable("KoiOrderDetails");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.KoiType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBatch")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEndangered")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("KoiTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9357),
                            IsBatch = true,
                            IsDeleted = false,
                            IsEndangered = false,
                            Name = "Kohaku",
                            Picture = "https://hanoverkoifarms.com/wp-content/uploads/2017/01/great-kohaku-739x1024.jpg",
                            UpdatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9358)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9360),
                            IsBatch = true,
                            IsDeleted = false,
                            IsEndangered = false,
                            Name = "Taisho Sanke",
                            Picture = "https://thucancakoihikari.com/wp-content/uploads/2024/04/koi-taisho-sanke-1.jpg",
                            UpdatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9361)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9362),
                            IsBatch = false,
                            IsDeleted = false,
                            IsEndangered = true,
                            Name = "Showa Sanshoku",
                            Picture = "https://cakoibienhoa.com/public/userfiles/products/ca-koi-showa-sanshoku-thumb.jpg",
                            UpdatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9363)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9364),
                            IsBatch = true,
                            IsDeleted = false,
                            IsEndangered = false,
                            Name = "Shusui",
                            Picture = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2qwYKPpE9yJJKYJ_npVzr3WzWvybWZK8-fQ&s",
                            UpdatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9364)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9365),
                            IsBatch = false,
                            IsDeleted = false,
                            IsEndangered = true,
                            Name = "Asagi",
                            Picture = "https://hanoverkoifarms.com/wp-content/uploads/2017/01/best-asagi.jpg",
                            UpdatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9366)
                        });
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsuranceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("KoiOderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InsuranceId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.OrderTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ConsultantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TripEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TripStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConsultantId");

                    b.HasIndex("FarmId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderTrips");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("ApprovalStatus")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuoteAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SalesStaffId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("SalesStaffId");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Maple St, Springfield, IL",
                            Avatar = "avatars/alice.jpg",
                            CreatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9255),
                            Email = "admin@gmail.com",
                            FullName = "Admin Johnson",
                            IsDeleted = false,
                            Password = "123456",
                            PhoneNumber = "123-456-7890",
                            Role = "Admin",
                            UpdatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9261)
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak St, Springfield, IL",
                            Avatar = "avatars/bob.jpg",
                            CreatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9267),
                            Email = "manager@gmail.com",
                            FullName = "Manager Smith",
                            IsDeleted = false,
                            Password = "securepass",
                            PhoneNumber = "234-567-8901",
                            Role = "Manager",
                            UpdatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9267)
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Pine St, Springfield, IL",
                            Avatar = "avatars/charlie.jpg",
                            CreatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9269),
                            Email = "staff@gmail.com",
                            FullName = "Staff Brown",
                            IsDeleted = false,
                            Password = "mypassword",
                            PhoneNumber = "345-678-9012",
                            Role = "Staff",
                            UpdatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9270)
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Cedar St, Springfield, IL",
                            Avatar = "avatars/diana.jpg",
                            CreatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9271),
                            Email = "customer@gmail.com",
                            FullName = "Customer Prince",
                            IsDeleted = false,
                            Password = "123456",
                            PhoneNumber = "456-789-0123",
                            Role = "Customer",
                            UpdatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9272)
                        },
                        new
                        {
                            Id = 5,
                            Address = "654 Birch St, Springfield, IL",
                            Avatar = "avatars/ethan.jpg",
                            CreatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9273),
                            Email = "ethan.hunt@example.com",
                            FullName = "Ethan Hunt",
                            IsDeleted = false,
                            Password = "missionimpossible",
                            PhoneNumber = "567-890-1234",
                            Role = "Staff",
                            UpdatedAt = new DateTime(2024, 11, 14, 20, 13, 0, 197, DateTimeKind.Local).AddTicks(9274)
                        });
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.Farm", b =>
                {
                    b.HasOne("KoiOrderingSystem_BusinessObject.User", "Manager")
                        .WithMany("Farms")
                        .HasForeignKey("ManagerId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.FarmKoiType", b =>
                {
                    b.HasOne("KoiOrderingSystem_BusinessObject.Farm", "Farm")
                        .WithMany("FarmKoiTypes")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KoiOrderingSystem_BusinessObject.KoiType", "KoiType")
                        .WithMany("FarmKoiTypes")
                        .HasForeignKey("KoiTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");

                    b.Navigation("KoiType");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.Feedback", b =>
                {
                    b.HasOne("KoiOrderingSystem_BusinessObject.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.Koi", b =>
                {
                    b.HasOne("KoiOrderingSystem_BusinessObject.Farm", "Farm")
                        .WithMany("Kois")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KoiOrderingSystem_BusinessObject.KoiType", "KoiType")
                        .WithMany("Kois")
                        .HasForeignKey("KoiTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Farm");

                    b.Navigation("KoiType");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.KoiByBatch", b =>
                {
                    b.HasOne("KoiOrderingSystem_BusinessObject.KoiType", "KoiType")
                        .WithMany()
                        .HasForeignKey("KoiTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KoiType");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.KoiOrder", b =>
                {
                    b.HasOne("KoiOrderingSystem_BusinessObject.Order", "Order")
                        .WithMany("KoiOders")
                        .HasForeignKey("OrderId");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.KoiOrderDetail", b =>
                {
                    b.HasOne("KoiOrderingSystem_BusinessObject.KoiByBatch", "KoiByBatch")
                        .WithOne("OrderDetailKoi")
                        .HasForeignKey("KoiOrderingSystem_BusinessObject.KoiOrderDetail", "KoiByBatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KoiOrderingSystem_BusinessObject.Koi", "Koi")
                        .WithMany("OrderDetailKois")
                        .HasForeignKey("KoiId");

                    b.HasOne("KoiOrderingSystem_BusinessObject.KoiOrder", "KoiOrder")
                        .WithMany("KoiOrderDetails")
                        .HasForeignKey("KoiOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Koi");

                    b.Navigation("KoiByBatch");

                    b.Navigation("KoiOrder");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.Order", b =>
                {
                    b.HasOne("KoiOrderingSystem_BusinessObject.User", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KoiOrderingSystem_BusinessObject.Insurance", null)
                        .WithMany("Orders")
                        .HasForeignKey("InsuranceId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.OrderTrip", b =>
                {
                    b.HasOne("KoiOrderingSystem_BusinessObject.User", "Consultant")
                        .WithMany("OrderTrips")
                        .HasForeignKey("ConsultantId");

                    b.HasOne("KoiOrderingSystem_BusinessObject.Farm", "Farm")
                        .WithMany("OrderTrips")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KoiOrderingSystem_BusinessObject.Order", "Order")
                        .WithMany("Trips")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultant");

                    b.Navigation("Farm");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.Payment", b =>
                {
                    b.HasOne("KoiOrderingSystem_BusinessObject.Currency", "Currency")
                        .WithMany("Payments")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KoiOrderingSystem_BusinessObject.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.Quote", b =>
                {
                    b.HasOne("KoiOrderingSystem_BusinessObject.Order", "Order")
                        .WithMany("Quotes")
                        .HasForeignKey("OrderId");

                    b.HasOne("KoiOrderingSystem_BusinessObject.User", "SalesStaff")
                        .WithMany()
                        .HasForeignKey("SalesStaffId");

                    b.Navigation("Order");

                    b.Navigation("SalesStaff");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.Currency", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.Farm", b =>
                {
                    b.Navigation("FarmKoiTypes");

                    b.Navigation("Kois");

                    b.Navigation("OrderTrips");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.Insurance", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.Koi", b =>
                {
                    b.Navigation("OrderDetailKois");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.KoiByBatch", b =>
                {
                    b.Navigation("OrderDetailKoi");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.KoiOrder", b =>
                {
                    b.Navigation("KoiOrderDetails");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.KoiType", b =>
                {
                    b.Navigation("FarmKoiTypes");

                    b.Navigation("Kois");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.Order", b =>
                {
                    b.Navigation("KoiOders");

                    b.Navigation("Payments");

                    b.Navigation("Quotes");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("KoiOrderingSystem_BusinessObject.User", b =>
                {
                    b.Navigation("Farms");

                    b.Navigation("OrderTrips");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
